CONTAINER_NAME="hue_timer"

LIGHT_ON_TIME="11:00"
LIGHT_OFF_TIME="20:00"
CO2_ON_TIME="10:00"
CO2_OFF_TIME="19:00"

LIGHT_SOCKET=20
CO2_SOCKET=19
BRIDGE_IP="192.168.1.10"

docker stop $CONTAINER_NAME
docker rm $CONTAINER_NAME
docker build --tag $CONTAINER_NAME --build-arg container_name=$CONTAINER_NAME .
docker run -d --name $CONTAINER_NAME --env CO2_ON_TIME=$CO2_ON_TIME --env CO2_OFF_TIME=$CO2_OFF_TIME --env CO2_SOCKET=$CO2_SOCKET --env LIGHT_ON_TIME=$LIGHT_ON_TIME --env LIGHT_OFF_TIME=$LIGHT_OFF_TIME --env LIGHT_SOCKET=$LIGHT_SOCKET --env BRIDGE_IP=$BRIDGE_IP --restart unless-stopped -v $(pwd)/:/$CONTAINER_NAME $CONTAINER_NAME

